[package]
name = "bootloader"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true

[features]
default = []
bsp_vsv = ["tock-registers"]

[[bin]]
name = "kernel"
path = "src/main.rs"

##--------------------------------------------------------------------------------------------------
## Dependencies
##--------------------------------------------------------------------------------------------------

[dependencies]

# Optional dependencies
tock-registers = { version = "0.8.x", default-features = false, features = ["register_types"], optional = true }

[target.'cfg(target_arch = "riscv64")'.dependencies]
riscv = "0.10.1"
