import pyfiglet, subprocess

def generate_header():
    return "// AUTOGENERATED DO NOT EDIT\n"

def generate_boot_logo():
    # Fonts: http://www.figlet.org/examples.html
    logo = pyfiglet.figlet_format("OpenThesis", font="larry3d", width=80)
    text = "pub fn print_boot_logo() {\n"
    for line in logo.split("\n"):
        text += f"\tprintln!(r\"{line}\");\n"
    text += "}"
    return text

def generate_version():
    sha = subprocess.check_output(["git", "rev-parse", "--short=8", "HEAD"]).decode().strip()
    return f"pub const SHA: &str = \"{sha}\";\n"

if __name__ == "__main__":
    with open("./src/helper.rs", "w") as f:
        f.write(generate_header() + "\n")
        f.write("use crate::println;"+ "\n")
        f.write(generate_boot_logo() + "\n")
        f.write(generate_version())
