# This is the default value but included for clarity
comment_width = 80
wrap_comments = true

format_code_in_doc_comments = true
doc_comment_code_block_width = 80

format_strings = true

hex_literal_case = "Upper"

imports_layout = "HorizontalVertical"

max_width = 80

normalize_comments = true
normalize_doc_attributes = true

reorder_impl_items = true
