// AUTOGENERATED DO NOT EDIT

use crate::println;
pub fn print_boot_logo() {
	println!(r" _____                          ______  __                                   ");
	println!(r"/\  __`\                       /\__  _\/\ \                     __           ");
	println!(r"\ \ \/\ \  _____      __    ___\/_/\ \/\ \ \___      __    ____/\_\    ____  ");
	println!(r" \ \ \ \ \/\ '__`\  /'__`\/' _ `\ \ \ \ \ \  _ `\  /'__`\ /',__\/\ \  /',__\ ");
	println!(r"  \ \ \_\ \ \ \L\ \/\  __//\ \/\ \ \ \ \ \ \ \ \ \/\  __//\__, `\ \ \/\__, `\");
	println!(r"   \ \_____\ \ ,__/\ \____\ \_\ \_\ \ \_\ \ \_\ \_\ \____\/\____/\ \_\/\____/");
	println!(r"    \/_____/\ \ \/  \/____/\/_/\/_/  \/_/  \/_/\/_/\/____/\/___/  \/_/\/___/ ");
	println!(r"             \ \_\                                                           ");
	println!(r"              \/_/                                                           ");
	println!(r"");
}
pub const SHA: &str = "05e251b1";
pub const  PUBLIC_KEY: &'static [u8] = include_bytes!("../tftp/public_key.pem");
