# Copyright (c) 2023-2024 Lawrence Hunter <lawrence.hunter@outlook.com>

on:
  push:
    branches:
      - main

name: Create release

jobs:
  build:
    name: Build project
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: |
          make
          make doc
          tar -zcvf doc.tar.gz target/riscv64gc-unknown-none-elf/doc/
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: pre-release
          release_name: Pre-release
          draft: true
          prerelease: true
      - name: Upload SentinelBoot Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./sentinel_boot
          asset_name: sentinel_boot
          asset_content_type: application/octet-stream
      - name: Upload docs Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./doc.tar.gz
          asset_name: docs.tar.gz
          asset_content_type: application/x-tar
