on:
  push:
    branches: ["main"]

name: Main CI

jobs:
  build:
    name: Build project
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: make
      - uses: actions/upload-artifact@v3
        with:
          name: bootloader
          path: ./bootloader

  # test:
  #   needs: build
  #   name: Test
  #   runs-on: self-hosted
  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: make test

  qemu_tftp:
    needs: build
    runs-on: [self-hosted, qemu]
    steps:
      - uses: actions/checkout@v3
      - run: |
          BSP=qemu make
          timeout 5m tftp/qemu_test.sh

  vf2_tftp:
    needs: qemu_tftp
    runs-on: [self-hosted, vf2]
    steps:
      - uses: actions/checkout@v3
      - run: |
          BSP=visionfive make
          rm /tftpboot/boot/*
          mv bootloader /tftpboot/boot
          cp tftp/{Image_vf2_signed.gz,rootfs.cpio.gz,jh7110-visionfive-v2.dtb,boot.scr,power_cycle_board.sh,board_serial_test.py} /tftpboot/boot
          cd /tftpboot/boot
          mv Image_vf2_signed.gz Image_signed.gz
          gzip --decompress Image_signed.gz
          gzip --decompress rootfs.cpio.gz
          chmod +x *.sh
          mkimage -A riscv -T script -O efi -C none -d boot.scr boot.scr.uimg
          ./power_cycle_board.sh off && ./power_cycle_board.sh on
          timeout 5m python3 board_serial_test.py
          ./power_cycle_board.sh off

  # hyperfine:
  #   needs: vf2_tftp
  #   runs-on: [self-hosted, vf2]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: |
  #         wget https://github.com/sharkdp/hyperfine/releases/download/v1.18.0/hyperfine-v1.18.0-aarch64-unknown-linux-gnu.tar.gz
  #         tar xvf hyperfine-v1.18.0-aarch64-unknown-linux-gnu.tar.gz
  #         BSP=qemu_tftp make
  #         hyperfine-v1.18.0-aarch64-unknown-linux-gnu/hyperfine --warmup 1 --show-output tftp/qemu_test.sh

  clippy:
    needs: vf2_tftp
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: make clippy

  Doc:
    needs: vf2_tftp
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: make doc
      - run: tar -zcvf doc.tar.gz target/riscv64gc-unknown-none-elf/doc/
      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: ./doc.tar.gz

  Geiger:
    needs: vf2_tftp
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: |
          make geiger || true
          cat .github/workflows/geiger.md >> $GITHUB_STEP_SUMMARY
