on:
  push:
    branches: [ "main" ]

name: CI

jobs:
  setup:
    name: Setup environment
    runs-on: self-hosted
    steps:
      - run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source "$HOME/.cargo/env"
          rustup toolchain install nightly-2023-04-09
          rustup target add riscv64gc-unknown-none-elf
          cargo install cargo-binutils
  build:
    needs: setup
    name: Build project
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: export TERM=xterm && make
  test:
    needs: [setup, build]
    name: Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: echo "⚠️⚠️ NO TESTING IMPLEMENTED ⚠️⚠️"
  Clippy:
    needs: [setup, build]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: export TERM=xterm && make clippy
