on:
  push:
    branches: [ "main" ]

name: CI

jobs:
  build:
    name: Build project
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          if ! [ -x "$(command -v docker)" ]; then
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
            groupadd docker || true
            usermod -aG docker $USER
            newgrp docker
          fi
          make clean && make
      - uses: actions/upload-artifact@v3
        with:
          name: bootloader.img
          path: ./bootloader.img
  test:
    needs: build
    name: Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          if ! [ -x "$(command -v docker)" ]; then
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
            groupadd docker || true
            usermod -aG docker $USER
            newgrp docker
          fi
          make test
  Clippy:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: |
          if ! [ -x "$(command -v docker)" ]; then
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
            groupadd docker || true
            usermod -aG docker $USER
            newgrp docker
          fi
          make clippy
  Doc:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: |
          if ! [ -x "$(command -v docker)" ]; then
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
            groupadd docker || true
            usermod -aG docker $USER
            newgrp docker
          fi
          make doc
          tar -zcvf doc.tar.gz target/riscv64gc-unknown-none-elf/doc/
      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: ./doc.tar.gz
