on:
  pull_request:
    branches: [ "main" ]

name: CI

jobs:
  build:
    name: Build project
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          if ! [ -x "$(command -v docker)" ]; then
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
            groupadd docker || true
            usermod -aG docker $USER
            newgrp docker
          fi
          make clean && make
  test:
    needs: build
    name: Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          if ! [ -x "$(command -v docker)" ]; then
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
            groupadd docker || true
            usermod -aG docker $USER
            newgrp docker
          fi
          make test
  Clippy:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: |
          if ! [ -x "$(command -v docker)" ]; then
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
            groupadd docker || true
            usermod -aG docker $USER
            newgrp docker
          fi
          make clippy

