on:
  pull_request:
    branches: ["main"]

name: Pull CI

jobs:
  build:
    name: Build project
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: make
      - uses: actions/upload-artifact@v3
        with:
          name: bootloader.img
          path: ./bootloader.img

  test:
    needs: build
    name: Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: make test

  qemu_tftp:
    needs: test
    runs-on: [self-hosted, qemu]
    steps:
      - uses: actions/checkout@v3
      - run: |
          BSP=qemu_tftp make
          mv bootloader.img /tftpboot/boot
          cp tftp/* /tftpboot/boot
          cd /tftpboot/boot
          chmod +x *.sh
          cd /tftpboot/boot
          rm boot.scr
          mv boot.scr.qemu boot.scr
          tar xvf Image.tar.gz
          tar xvf rootfs.ext4.tar.gz
          ./mkimage.sh
          timeout 5m ./qemu_tftp.sh

  vf2_tftp:
    needs: qemu_tftp
    runs-on: [self-hosted, vf2]
    steps:
      - uses: actions/checkout@v3
      - run: |
          BSP=visionfive make
          mv bootloader.img /tftpboot/boot
          cp tftp/* /tftpboot/boot
          cd /tftpboot/boot
          tar xvf Image.tar.gz
          chmod +x *.sh
          ./mkimage.sh
          ./power_vf2.sh off && ./power_vf2.sh on
          timeout 5m python3 vf2_tftp.py
          ./power_vf2.sh off

  hyperfine:
    needs: vf2_tftp
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: |
          make
          make hyperfine
          cat test.md >> $GITHUB_STEP_SUMMARY

  clippy:
    needs: vf2_tftp
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: make clippy

  Doc:
    needs: vf2_tftp
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: make doc
      - run: tar -zcvf doc.tar.gz target/riscv64gc-unknown-none-elf/doc/
      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: ./doc.tar.gz

  Geiger:
    needs: vf2_tftp
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: |
          make geiger || true
          cat .github/workflows/geiger.md >> $GITHUB_STEP_SUMMARY
