on:
  pull_request:
    branches: [ "main" ]

name: Pull CI

jobs:
  build:
    name: Build project
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: |
          if ! [ -x "$(command -v docker)" ]; then
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
            groupadd docker || true
            usermod -aG docker $USER
            newgrp docker
          fi
          make clean && make
      - uses: actions/upload-artifact@v3
        with:
          name: bootloader.img
          path: ./bootloader.img
  test:
    needs: build
    name: Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: |
          if ! [ -x "$(command -v docker)" ]; then
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
            groupadd docker || true
            usermod -aG docker $USER
            newgrp docker
          fi
          if ! [ -x "$(command -v qemu-system-riscv64)" ]; then
            apt install -y qemu-system
          fi
          echo "# Test summary\n"
          make test >> $GITHUB_STEP_SUMMARY
  clippy:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: |
          if ! [ -x "$(command -v docker)" ]; then
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
            groupadd docker || true
            usermod -aG docker $USER
            newgrp docker
          fi
          make clippy >> $GITHUB_STEP_SUMMARY
  Doc:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: |
          if ! [ -x "$(command -v docker)" ]; then
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
            groupadd docker || true
            usermod -aG docker $USER
            newgrp docker
          fi
          make doc
          tar -zcvf doc.tar.gz target/riscv64gc-unknown-none-elf/doc/
      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: ./doc.tar.gz
  Call_stack:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: |
          if ! [ -x "$(command -v docker)" ]; then
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
            groupadd docker || true
            usermod -aG docker $USER
            newgrp docker
          fi
          make call_stack
          echo "<img src="./cg.svg">" >> $GITHUB_STEP_SUMMARY
      - uses: actions/upload-artifact@v3
        with:
          name: call_stack
          path: ./call_stack.svg
