on:
  pull_request:
    branches: ["main"]

name: Pull CI

jobs:
  gen_docker_vf2:
    name: Build docker image for vf2 pi
    runs-on: [self-hosted, vf2]
    steps:
      - uses: actions/checkout@v3
      - run: docker build --tag bootloader --file Dockerfile .
    timeout-minutes: 60
  gen_docker_sp4:
    name: Build docker image for sp4 pi
    runs-on: [self-hosted, sp4]
    steps:
      - uses: actions/checkout@v3
      - run: docker build --tag bootloader --file Dockerfile .
    timeout-minutes: 60
  build:
    name: Build project
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: make
      - uses: actions/upload-artifact@v3
        with:
          name: bootloader.img
          path: ./bootloader.img
  test:
    needs: build
    name: Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "# Test summary\n" >> $GITHUB_STEP_SUMMARY
          make test >> $GITHUB_STEP_SUMMARY
  clippy:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: |
          make clippy >> $GITHUB_STEP_SUMMARY
  Doc:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: |
          make doc
          tar -zcvf doc.tar.gz target/riscv64gc-unknown-none-elf/doc/
      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: ./doc.tar.gz
  Call_stack:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: make call_stack
      - uses: actions/upload-artifact@v3
        with:
          name: Call graph
          path: ./cg.svg
  Guess_unsafe_count:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "# Crude unsafe line estimate" >> $GITHUB_STEP_SUMMARY
          echo "Count: " >> $GITHUB_STEP_SUMMARY
          grep -r -E "unsafe\s?\{" | wc -l >> $GITHUB_STEP_SUMMARY
  Geiger:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo '```' >> $GITHUB_STEP_SUMMARY
          make geiger >> $GITHUB_STEP_SUMMARY || true
          echo '```' >> $GITHUB_STEP_SUMMARY
  tftp:
    needs: build
    runs-on: [self-hosted, vf2]
    steps:
      - uses: actions/checkout@v3
      - run: |
          make
          mv bootloader.img /tftpboot/boot
          cp tftp/* /tftpboot/boot
          cd /tftpboot/boot
          chmod +x *.sh
          ./mkimage.sh
          ./power_vf2.sh off && ./power_vf2.sh on
          echo '```' >> $GITHUB_STEP_SUMMARY
          timeout 5m python3 vf2_tftp.py >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          ./power_vf2.sh off
  qemu_tftp:
    needs: build
    runs-on: [self-hosted, qemu]
    steps:
      - uses: actions/checkout@v3
      - run: |
          make
          mv bootloader.img /tftpboot/boot
          cp tftp/* /tftpboot/boot
          cd /tftpboot/boot
          chmod +x *.sh
          cd /tftpboot/boot
          ./mkimage.sh
          echo '```' >> $GITHUB_STEP_SUMMARY
          timeout 5m ./qemu_tftp.sh >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
